name: Build on Ubuntu 22.04

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download ccache cache
        uses: actions/cache@v2
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-ccache-${{ hashFiles('**/build.sh') }}
          restore-keys: ${{ runner.os }}-ccache-

      - name: Install ccache
        run: sudo apt-get install -y ccache

      - name: Set up ccache
        run: |
          echo 'export PATH="/usr/lib/ccache:$PATH"' >> $GITHUB_ENV
          export CCACHE_DIR=/tmp/ccache
          mkdir -p $CCACHE_DIR
          echo "CCACHE_DIR=$CCACHE_DIR" >> $GITHUB_ENV

      - name: Run build script
        run: |
          sh -ex ./build.sh

      - name: Upload ccache cache
        uses: actions/cache@v2
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ${{ runner.os }}-ccache-${{ hashFiles('**/build.sh') }}
          
      - name: Upload to GitHub Releases
        if: github.event_name != 'pull_request' && github.ref_name == 'main'
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "continuous"
          prerelease: false
          title: "Continuous Build"
          files: |
            ./serenity/Ladybird/Ladybird-*.AppImage*
